"""Capture a Pocket Option Playwright session and upload it to a connect URL."""

from __future__ import annotations

import argparse
import asyncio
import json
from pathlib import Path

import httpx

from app.config.settings import get_settings


def build_parser() -> argparse.ArgumentParser:
    """Create the command-line interface for session capture and upload."""

    parser = argparse.ArgumentParser(
        description=(
            "Open Pocket Option in Chromium, let the user log in, capture "
            "Playwright storage state, and upload it to the secure connect URL."
        )
    )
    parser.add_argument("connect_url", help="Secure connect URL generated by /connect")
    parser.add_argument(
        "--trade-amount",
        type=int,
        default=None,
        help="Trade amount stored for this user profile",
    )
    parser.add_argument(
        "--expiry",
        default=None,
        help="Expiration label stored for this user profile, for example M5",
    )
    parser.add_argument(
        "--horizon",
        default="1m",
        choices=["5s", "10s", "30s", "1m"],
        help="Signal horizon used for autotrade",
    )
    parser.add_argument(
        "--autotrade",
        action="store_true",
        help="Enable autotrade immediately after connecting the session",
    )
    parser.add_argument(
        "--save-local",
        action="store_true",
        help="Also save the captured storage state to POCKET_OPTION_STORAGE_STATE_PATH",
    )
    return parser


async def main() -> None:
    """Capture the session and post it to the connect endpoint."""

    try:
        from playwright.async_api import async_playwright
    except ImportError as exc:
        raise RuntimeError(
            "Playwright is required. Install requirements-browser.txt and run "
            "'python -m playwright install chromium'."
        ) from exc

    args = build_parser().parse_args()
    settings = get_settings()

    async with async_playwright() as playwright:
        browser = await playwright.chromium.launch(headless=False)
        context = await browser.new_context()
        page = await context.new_page()
        await page.goto(settings.pocket_option_base_url, wait_until="domcontentloaded")

        print("Pocket Option login window opened.")
        print("1. Log in to your Pocket Option account in the browser.")
        print("2. Wait until the trading screen is fully visible.")
        print("3. Press Enter here to capture and upload the session.")
        input()

        storage_state = await context.storage_state()
        if args.save_local:
            storage_state_path = Path(settings.pocket_option_storage_state_path).expanduser()
            storage_state_path.parent.mkdir(parents=True, exist_ok=True)
            storage_state_path.write_text(json.dumps(storage_state, indent=2), encoding="utf-8")
            print(f"Saved local storage state to {storage_state_path}")

        payload = {
            "storage_state": json.dumps(storage_state),
            "autotrade_enabled": args.autotrade,
            "trade_amount": args.trade_amount or settings.pocket_option_trade_amount,
            "expiration_label": args.expiry or settings.pocket_option_expiration_label,
            "signal_horizon": args.horizon,
        }

        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(args.connect_url, json=payload)

        await browser.close()

    if response.is_success:
        print("Session uploaded successfully.")
        print(response.text)
        return

    raise RuntimeError(
        f"Upload failed with HTTP {response.status_code}: {response.text}"
    )


if __name__ == "__main__":
    asyncio.run(main())
